# Generated by Django 3.1.3 on 2020-11-21 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cleaning',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='クリーニング'),
        ),
        migrations.AddField(
            model_name='item',
            name='dataerase',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='データイレース'),
        ),
        migrations.AddField(
            model_name='item',
            name='datanyuuryoku',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='データ・画像登録'),
        ),
        migrations.AddField(
            model_name='item',
            name='nyuukosyouhinka',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='入庫商品化'),
        ),
        migrations.AddField(
            model_name='item',
            name='picking',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='搬出・ピッキング'),
        ),
        migrations.AddField(
            model_name='item',
            name='shiirePC',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='仕入PC'),
        ),
        migrations.AddField(
            model_name='item',
            name='shiiresyouhinka',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='仕入商品化'),
        ),
        migrations.AddField(
            model_name='item',
            name='takuhaikaikon',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='宅配開梱・登録'),
        ),
        migrations.AddField(
            model_name='item',
            name='tsutaya',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='TSUTAYA関連'),
        ),
    ]
