# Generated by Django 3.1.3 on 2020-11-21 12:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0003_auto_20201121_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nyuukosyouhinka',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='入庫商品化'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picking',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8.0)], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='sonotakenpin',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='その他検品'),
        ),
        migrations.AlterField(
            model_name='item',
            name='takuhaikaikon',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=1, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8.0)], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='takuhaikenpin',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='宅配検品'),
        ),
    ]
