# Generated by Django 3.1.3 on 2020-11-22 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0006_auto_20201121_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cleaning',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='クリーニング(@50)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dataerase',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='データイレース(@50)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='datanyuuryoku',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='データ入力・画像登録(h)※0.5h刻みで入力'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nyuukosyouhinka',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='入庫商品化(@200)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picking',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='搬出・ピッキング(h)※0.5h刻みで入力'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shiirePC',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='仕入PC(@1000)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='shiiresyouhinka',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='仕入商品化(@100)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sonotakenpin',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='その他検品(@200)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='takuhaikaikon',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric are allowed.')], verbose_name='宅配開梱(h)※0.5h刻みで入力'),
        ),
        migrations.AlterField(
            model_name='item',
            name='takuhaikenpin',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='宅配検品(@400)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tsutaya',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='TSUTAYA関連(h)※0.5h刻みで入力'),
        ),
    ]
