# Generated by Django 3.1.3 on 2020-11-22 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DailyReport', '0008_auto_20201122_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picking',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(8.0)], verbose_name='搬出・ピッキング(h)※0.5h刻みで入力'),
        ),
        migrations.AlterField(
            model_name='item',
            name='takuhaikaikon',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='宅配開梱(h)※0.5h刻みで入力'),
        ),
    ]
